import "./aga.css";

const services = [
  ["01","Home repairs","Drywall, fixtures, appliances, furniture assembly, and the small jobs that keep a home working."],
  ["02","Remodeling","Bathroom updates, flooring, painting, and finish work handled from start to finish."],
  ["03","Outdoor projects","Deck and fence repairs, pressure washing, gutter cleaning, hauling, and seasonal upkeep."],
];

export default function AgaDemo(){
  return <main className="aga-site">
    <div className="concept-bar">PRIVATE CONCEPT REDESIGN BY SITEGLOW <span>Not affiliated with or endorsed by AGA Handyman Services</span></div>
    <header className="aga-nav wrap"><a className="aga-brand" href="#top"><span>AGA</span><div><b>HANDYMAN SERVICES</b><small>SUPERIOR SERVICE &amp; QUALITY</small></div></a><nav><a href="#services">Services</a><a href="#about">About</a><a href="#areas">Service areas</a></nav><a className="aga-phone" href="tel:4256261277"><small>CALL OR TEXT</small><b>(425) 626-1277</b></a></header>
    <section className="aga-hero" id="top"><div className="aga-photo"/><div className="aga-hero-copy wrap"><p className="aga-kicker">KIRKLAND’S LOCAL HANDYMAN</p><h1>One trusted team.<br/><em>Every job done right.</em></h1><p>From the small fixes on your list to full room updates, AGA brings 20+ years of hands-on experience to homes across the Eastside.</p><div><a className="aga-button" href="mailto:service@agahandyman.com?subject=Project estimate request">Get a free estimate <span>→</span></a><a className="aga-text" href="#services">Explore services ↓</a></div></div><div className="aga-proof"><div><b>20+</b><span>Years of<br/>experience</span></div><div><b>A+</b><span>BBB<br/>rating</span></div><div><b>100%</b><span>Licensed, bonded<br/>&amp; insured</span></div></div></section>
    <section className="aga-intro wrap" id="about"><div><p className="aga-kicker">THE AGA DIFFERENCE</p><h2>Your project is personal.<br/><em>We treat it that way.</em></h2></div><div><p>AGA Handyman Services is a family-owned Kirkland business built on integrity, professionalism, and work that lasts. We coordinate reliable, fully insured tradespeople so you have one team to call—no matter the size of the job.</p><div className="aga-checks"><span>✓ Clear communication</span><span>✓ Competitive pricing</span><span>✓ Reliable workmanship</span><span>✓ Respect for your home</span></div></div></section>
    <section className="aga-services" id="services"><div className="wrap"><p className="aga-kicker">HOW WE CAN HELP</p><div className="service-heading"><h2>Big projects.<br/><em>Small chores.</em></h2><p>If it needs fixing, refreshing, installing, or improving, there’s a good chance AGA can handle it.</p></div><div className="aga-service-grid">{services.map(([num,title,body])=><article key={num}><span>{num}</span><div className="service-shape"/><h3>{title}</h3><p>{body}</p><a href="mailto:service@agahandyman.com?subject=Project estimate request">Discuss your project →</a></article>)}</div></div></section>
    <section className="aga-areas wrap" id="areas"><div className="area-card"><p className="aga-kicker">PROUDLY SERVING THE EASTSIDE</p><h2>Your neighborhood<br/><em>handyman team.</em></h2><p>Kirkland · Bellevue · Redmond · Bothell<br/>Woodinville · Sammamish · Issaquah</p></div><div className="area-quote"><span>“</span><p>Rest assured, your projects are our top priority and will be performed with integrity and professionalism.</p><small>THE AGA PROMISE</small></div></section>
    <section className="aga-cta"><div className="wrap"><div><p className="aga-kicker">LET’S CHECK IT OFF YOUR LIST</p><h2>Tell us what<br/><em>needs doing.</em></h2></div><div><p>Share a few details about your project. We’ll get back to you with the next steps and a straightforward estimate.</p><a className="aga-button light" href="mailto:service@agahandyman.com?subject=Project estimate request">Request an estimate <span>→</span></a><a className="cta-phone" href="tel:4256261277">Or call/text (425) 626-1277</a></div></div></section>
    <footer className="aga-footer wrap"><a className="aga-brand" href="#top"><span>AGA</span><div><b>HANDYMAN SERVICES</b><small>SUPERIOR SERVICE &amp; QUALITY</small></div></a><p>Licensed · Bonded · Insured<br/>Contractor #AGAHAHS837PT</p><p>service@agahandyman.com<br/>(425) 626-1277</p></footer>
  </main>
}
